#!/bin/zsh
trap 'rm -f /tmp/raw_species.json' EXIT
trap 'rm -f /tmp/raw_evolution.json' EXIT

API_URL="https://pokeapi.co/api/v2/"
VERSION="1.2.0"

# Flags
pokemon=""
types=false
forms=false
eggs=false
help=false
img_type=dex
img_ext=png

# Fancy Formating
BOLD="\e[1m"
RESET="\e[0m"
MAGENTA="\e[35m"
UNDERLINE="\e[4m"
TPUT_ROW=1
TPUT_COL=35

# Container Variables
curled=""
stage_one=null
stage_two=null

# Clear Screen for Image
tput clear

# Set All Pokemon Variables
allpokemon() {
    forms=true
    types=true
    eggs=true
}

# Flag Settings
while [[ "$#" -gt 0 ]]
do case $1 in
    -p|--pokemon) pokemon="$2"
    shift 2;;
    -t|--types) types=true
    shift;;
    -f|--forms) forms=true
    shift;;
    -e|--egg-groups) eggs=true
    shift;;
    -a|--all-pokemon) allpokemon
    shift;;
    --animated-image) 
        img_type="ani"
        img_ext="gif"
    shift;;
    --shiny-image) img_type="dex-shiny"
    shift;;
    -h|--help) help=true
    shift;;
    -v|--version)
        echo "Pokefetcher v$VERSION"
        exit 0
    shift;;
    *) echo "Unknown option: $1"
    exit 1
    ;;
esac
done

# Function for Printing with tput
tprint() {
    local Line
    while IFS= read -r line; do
        if [[ -n "$KITTY_WINDOW_ID" ]]; then
            tput cup $TPUT_ROW $TPUT_COL
            echo "$line"
            ((TPUT_ROW++))
        else
            echo $1
        fi
    done <<< "$1"
}

# Species Data Fetch
speciesfetch() {
    species_url=$(echo "$curled" | jq -r '.species.url')
    species_data=$(curl -s "$species_url" > /tmp/raw_species.json)
}

# Types
typesfetch() {
    if $types; then
        tprint "${BOLD}Types${RESET}:"
        tmp_out=$(echo "$curled" | jq -r '.types[].type.name' | sed 's/^/  /')
        tprint "$tmp_out"
    fi
}

# Forms
formsfetch() {
    if $forms; then
        tprint "${BOLD}Forms${RESET}:"
        tmp_out=$(cat /tmp/raw_species.json | jq -r '.varieties[].pokemon.name' | sed 's/^/  /')
        tprint "$tmp_out"
    fi
}

# Evolutions
evosfetch() {
    evolution_url=$(cat /tmp/raw_species.json | jq -r '.evolution_chain.url')
    evolution_data=$(curl -s "$evolution_url" > /tmp/raw_evolution.json)
    evolutions=$(cat /tmp/raw_evolution.json | jq -r '.chain.evolves_to[]')

    basic=$(cat /tmp/raw_evolution.json | jq -r '.chain.species.name')
    stage_one=$(echo $evolutions | jq -r '.species.name')
    stage_two=$(echo $evolutions | jq -r '.evolves_to[].species.name')

    tprint "${BOLD}Evolution Line${RESET}:"
    tprint " ${UNDERLINE}$basic${RESET} ${UNDERLINE}$stage_one${RESET} ${UNDERLINE}$stage_two${RESET}\n"
}

# Egg Group(s)
eggfetch() {
    if $eggs; then
        tprint "${BOLD}Egg Groups${RESET}:"
        tmp_out=$(cat /tmp/raw_species.json | jq -r '.egg_groups[].name' | sed 's/^/  /')
        tprint "$tmp_out"
    fi
}

# Stats


# Gender Ratio


# Image
imagefetch() {
    IMAGE_URL="https://play.pokemonshowdown.com/sprites/$img_type/$pokemon.$img_ext"
    kitten icat --place 20x20@3x2 --scale-up $IMAGE_URL
}


# Main Function
pokefetch() {
    # Curl the API
    pokemon=$1
    curled=$(curl -s $API_URL/pokemon/$pokemon)

    # Handle Invalid Pokemon
    if [[ -z "$curled" || "$curled" == "Not Found" ]]; then
        echo "Error: Pokémon '$pokemon' not found."
        exit 1
    fi

    # Echo Name, ID, and Image
    name=$(echo "$curled" | jq -r .name | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')
    id=$(echo "$curled" | jq -r .id)
    echo "${BOLD}${MAGENTA}$name${RESET}, ID:${BOLD}$id${RESET}"
    imagefetch

    # Curl the pokemon-species page for evosfetch and formsfetch
    speciesfetch

    # Call Aux. Functions
    evosfetch
    typesfetch
    formsfetch
    eggfetch
}

help() {
    echo "Welcome to Pokefetcher, a simple PokeAPI interface!
    
    Use:
     pokefetcher -p <pokemon> [flags]
     
    Flags:
     -t, --types       Displays the Pokemon's Typing
     -f, --forms       Displays Variant forms (Regional, GMAX, Mega...)
     -e, --egg-groups  Displays Egg Groups
     -a, --all-pokemon Acts as both --types and --forms
     -h, --help        Displays this here help message!
     -v, --version     Displays current Pokefetcher version"
}

if $help; then
    help
elif [[ "$pokemon" != "" ]]; then
    pokefetch "$pokemon"
else
    echo "Usage: $0 -p <pokemon> [-t] [-f]"
fi